- id: '1731173374620'
  alias: HP watertemperatuur setpoint
  description: ''
  triggers:
  - entity_id:
    - sensor.stooklijn_target
    trigger: state
  conditions: []
  actions:
  - action: modbus.write_register
    data:
      hub: HP_modbus_hub
      slave: 1
      address: 2
      value: '{{ (states(''sensor.hp_watertemperatuur_setpoint'') | float(0) | round(0))
        * 10 }}'
  mode: single
- id: '1696873855292'
  alias: HP Hotstart
  description: ''
  triggers:
  - trigger: template
    value_template: '{{ (states(''sensor.hp_water_outlet_temp'') | float(0) - (states(''sensor.hp_watertemperatuur_setpoint'')
      | float(0))) > 3}}'
  - trigger: template
    value_template: '{{ (states(''sensor.hp_water_outlet_temp'') | float(0) - (states(''sensor.hp_watertemperatuur_setpoint'')
      | float(0))) < 2}}'
  actions:
  - repeat:
      sequence:
      - data: {}
        target:
          entity_id: input_number.hp_hotstart_offset
        action: input_number.increment
      while:
      - condition: template
        value_template: '{{ ((states(''sensor.hp_water_outlet_temp'') | float(0) -
          (states(''sensor.hp_watertemperatuur_setpoint'') | float(0)))) > 3 }}'
  - repeat:
      sequence:
      - data: {}
        target:
          entity_id: input_number.hp_hotstart_offset
        action: input_number.decrement
      while:
      - condition: template
        value_template: '{{ ((states(''sensor.hp_water_outlet_temp'') | float(0) -
          (states(''sensor.hp_watertemperatuur_setpoint'') | float(0)))) < 2 }}'
      - condition: numeric_state
        entity_id: input_number.hp_hotstart_offset
        above: 0
  mode: single
- id: '16963453855292'
  alias: HP Thermostaat
  description: ''
  triggers:
  - trigger: template
    id: temp_too_high
    value_template: '{{ (states(''input_number.thermostat_target'') | float(0) + (states(''input_number.thermostat_hysteresis'')
      | float(0))) < states(''sensor.Binnentemperatuur placeholder'') | float(0)}}'
  - trigger: template
    id: temp_too_low
    value_template: '{{ (states(''input_number.thermostat_target'') | float(0) - (states(''input_number.thermostat_hysteresis'')
      | float(0))) > states(''sensor.Binnentemperatuur placeholder'') | float(0)}}'
  actions:
  - if:
    - condition: trigger
      id:
      - temp_too_high
    then:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.hp_switch_onoff
  - if:
    - condition: trigger
      id:
      - temp_too_low
    then:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.hp_switch_onoff
  mode: single
