alias: HP - Silent mode off na defrost
description: ""
triggers:
  - entity_id:
      - binary_sensor.hp_defrosting_status
    to: "off"
    from: "on"
    for:
      hours: 0
      minutes: 8
      seconds: 0
    trigger: state
conditions:
  - condition: state
    entity_id: switch.hp_switch_onoff
    state: "on"
  - condition: numeric_state
    entity_id: sensor.Buitentemperatuur_placeholder
    below: 6
actions:
  - wait_for_trigger:
      - entity_id:
          - sensor.hp_compressor_hz
        below: 40
        trigger: numeric_state
    continue_on_timeout: false
    timeout:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - data: {}
    target:
      entity_id: switch.hp_switch_silent
    action: switch.turn_off
mode: single

alias: HP - Silent mode aan bij defrost
description: ""
triggers:
  - entity_id:
      - binary_sensor.hp_defrosting_status
    to: "on"
    trigger: state
  - entity_id:
      - sensor.hp_compressor_hz
    above: 45
    trigger: numeric_state
  - entity_id:
      - switch.hp_switch_onoff
    from: "off"
    to: "on"
    trigger: state
conditions: []
actions:
  - data: {}
    target:
      entity_id: switch.hp_switch_silent
    action: switch.turn_on
mode: single
