
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
modbus: !include modbus.yaml

input_number:
  stooklijn_min_oat:
    name: "Stooklijn Minimum Buitentemperatuur"
    min: -15
    max: 4
    step: 1
    unit_of_measurement: "°C"
    mode: box
  stooklijn_max_oat:
    name: "Stooklijn Maximum Buitentemperatuur"
    min: 5
    max: 20
    step: 1
    unit_of_measurement: "°C"
    mode: box
  stooklijn_max_wtemp:
    name: "Stooklijn Maximum Watertemperatuur"
    min: 31
    max: 50
    step: 1
    unit_of_measurement: "°C"
    mode: box
  stooklijn_min_wtemp:
    name: "Stooklijn Minimum Watertemperatuur"
    min: 20
    max: 30
    step: 1
    unit_of_measurement: "°C"
    mode: box
  hp_hotstart_offset:
    name: "HP Hotstart offset"
    min: 0
    max: 10
    step: 1
    unit_of_measurement: "°C"
    mode: box

template:
  - sensor:
      - name: "Stooklijn Target"
        unique_id: Stooklijn_Target_id
        unit_of_measurement: "°C"
        state: >
          {% set oat = states('sensor.HP_outdoor_air_temp') | float(0) %}
          {% set  z = ((states('input_number.stooklijn_min_wtemp') | float(0)) - (states('input_number.stooklijn_max_wtemp') | float(0) )) / ((states('input_number.stooklijn_max_oat') | float(0) ) - (states('input_number.stooklijn_min_oat') | float(0) )) %}
          {% if oat < (states('input_number.stooklijn_min_oat') | float(0)) %}
          {% set oat = states('input_number.stooklijn_min_oat') | float(0) %}
          {% endif %}
          {% if oat > (states('input_number.stooklijn_max_oat') | float(0)) %}
          {% set oat = states('input_number.stooklijn_max_oat') | float(0) %}
          {% endif %}
          {{ (z * (oat - states('input_number.stooklijn_min_oat') | float(0) ) + (states('input_number.stooklijn_max_wtemp') | float(0) )) | round(default=20) }}
